### ISSUE TITLE
Add debug_assert_nearly_eq

### ISSUE THREAD

**Issue by Robbepop** [chalharu/rust-nearly-eq#19]
The rust standard library defines a [debug_assert](https://doc.rust-lang.org/std/macro.debug_assert.html) macro corresponding to the [assert](https://doc.rust-lang.org/std/macro.assert.html) macro that is activated only in debug mode but disabled in release builds to not negatively impact release build performance.

You may want this for your library as `debug_assert_nearly_eq`.

**Comment by chalharu** [comment]
Implemented
